# Generated by Django 4.1.2 on 2023-05-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods', models.IntegerField(choices=[(0, 'Rice'), (1, 'Bulgogi')])),
                ('drinks', models.IntegerField(choices=[(0, 'Coffee'), (1, 'Tea')])),
                ('table', models.BooleanField()),
                ('tent', models.BooleanField()),
            ],
        ),
    ]
