# Generated by Django 4.1.2 on 2023-05-08 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
    ]
