# Generated by Django 4.1.2 on 2023-05-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_menu_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='event_date',
            field=models.DateTimeField(null=True),
        ),
    ]
