# Generated by Django 4.1.2 on 2023-05-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_menu_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='event_date',
        ),
    ]
