# Generated by Django 4.1.2 on 2023-05-09 03:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_drink_food_remove_menu_drinks_remove_menu_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='drinks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='menu',
            name='foods',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], default=0, max_length=3),
        ),
    ]
