# Generated by Django 4.1.2 on 2023-05-09 10:37

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_menu_drinks_menu_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'tea'), (2, 'coffee'), (3, 'fizzy'), (4, 'water')], max_length=3),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'heavy'), (2, 'light'), (3, 'soup'), (4, 'dessert'), (5, 'fruit')], max_length=3),
        ),
        migrations.AlterField(
            model_name='menu',
            name='drinks',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=200),
        ),
        migrations.AlterField(
            model_name='menu',
            name='foods',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=200),
        ),
        migrations.CreateModel(
            name='testMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testDrinks', models.ManyToManyField(to='api.drink')),
                ('testFoods', models.ManyToManyField(to='api.food')),
            ],
        ),
    ]
