# Generated by Django 4.1.2 on 2023-05-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_drink_category_alter_food_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='drink',
            name='category',
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='foods',
        ),
        migrations.DeleteModel(
            name='testMenu',
        ),
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.ManyToManyField(to='api.drinkcategory'),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ManyToManyField(to='api.foodcategory'),
        ),
        migrations.AddField(
            model_name='menu',
            name='drinks',
            field=models.ManyToManyField(to='api.drink'),
        ),
        migrations.AddField(
            model_name='menu',
            name='foods',
            field=models.ManyToManyField(to='api.food'),
        ),
    ]
