# Generated by Django 4.1.2 on 2023-05-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_drinkcategory_foodcategory_remove_drink_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ticket_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
