# Generated by Django 4.1.2 on 2023-05-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_customer_ticket_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='customer',
        ),
    ]
