# Generated by Django 4.1.2 on 2023-05-17 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_date_customer'),
    ]

    operations = [
    ]
