# Generated by Django 4.1.2 on 2023-05-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_customer_address_alter_foodcategory_name'),
        ('api', '0017_alter_food_category'),
    ]

    operations = [
    ]
