# Generated by Django 4.1.2 on 2023-05-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image_location',
            field=models.CharField(blank=True, default='images/food_images/', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=5000),
        ),
    ]
