# Generated by Django 4.1.2 on 2023-05-17 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.set'),
        ),
    ]
