# Generated by Django 4.1.2 on 2023-05-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_food_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='set',
        ),
        migrations.AddField(
            model_name='set',
            name='foods',
            field=models.ManyToManyField(to='api.food'),
        ),
    ]
