# Generated by Django 4.1.2 on 2023-05-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_food_set_set_foods'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.set'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_set',
            field=models.BooleanField(default=False),
        ),
    ]
