# Generated by Django 4.1.2 on 2023-05-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_menu_food_set_menu_is_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='foods',
            new_name='custom_menu',
        ),
    ]
